### ISSUE TITLE
[WIP] Epic: Automate infrastructure using IaC

### ISSUE THREAD

**Issue by silopolis** [DevOps-Boot/fastapi-k8s#27]
- [ ] Automate infrastructure provisioning
- [ ] Automate IAM provisioning
- [ ] Automate infrastructure configuration
