### ISSUE TITLE
[WIP] Epic: Data layer architecture

### ISSUE THREAD

**Issue by silopolis** [DevOps-Boot/fastapi-k8s#28]
- [ ] Define data types and sources
- [ ] Define nature, velocity and volume of data for the application
- [ ] Define data architecture, including how to link different data together
- [ ] Select technical storage solution(s) (RDBMS, NoSQL, File/Block/Object storage)
