### ISSUE TITLE
Epic: Create data layer

### ISSUE THREAD

**Issue by silopolis** [DevOps-Boot/fastapi-k8s#29]
- [ ] Provision and configure storage resources
- [ ] Setup access rights
- [ ] Cleanup, format and ingest data
- [ ] Test data access and rights
- [ ] Configure and schedule data backup
