### ISSUE TITLE
Epic: Continuous deployment

### ISSUE THREAD

**Issue by silopolis** [DevOps-Boot/fastapi-k8s#35]
- [ ] Design CD pipeline(s) automating packaging and deployment into a 'prod' environment; optionally, create a 'dev' environment for developers to use the pipeline(s) or its steps on demand
- [ ] Implement CD pipeline(s)
- [ ] Choose and implement CD strategy (Canary, Blue/Green)
