### ISSUE TITLE
Epic: Monitoring and observability system design

### ISSUE THREAD

**Issue by silopolis** [DevOps-Boot/fastapi-k8s#38]
- [ ] Define logs, metrics, "health points", thresholds and events collection requirements
- [ ] Define dashboard requirements
- [ ] Define actions and alerting requirements
- [ ] Select logs, metrics and events collection and centralization solutions
- [ ] Design monitoring and observability architecture
