### ISSUE TITLE
Epic: Build monitoring and observability infrastructure

### ISSUE THREAD

**Issue by silopolis** [DevOps-Boot/fastapi-k8s#39]
- [ ] Provision and configure logs centralization infrastructure
- [ ] Provision and configure metrics collection and storage
- [ ] Provision events collection and detection
- [ ] Provision alerting
