### ISSUE TITLE
Epic: Configure monitoring and observability system

### ISSUE THREAD

**Issue by silopolis** [DevOps-Boot/fastapi-k8s#40]
- [ ] Enable "health points", thresholds and events checking
- [ ] Setup and configure dashboards
- [ ] Setup and configure actions and alerts
